Proof-of-concept how to block YouTube ads.
ghostery/adblocker pull request #2725
Opened 2022-07-25 10:31 UTC by philipp-classen

Background: the current mechanism to inject scriptlets by asynchronously responding to messages from the content script is not reliable. Because of the asynchronous communication, it is possible that the website already executed and the patching is too late.

A more reliable approach is to use the "tabs.executeScript" API and to use the webNavigation.onCommitted hook to trigger it.

2022-07-28 08:05 UTC, remusao requested changes

2022-07-28 08:05 UTC, remusao commented on packages/adblocker-webextension/adblocker.ts
> +      // TODO: Redundant now, or still needed (e.g. what happens if there
Does the onCommitted listener also trigger on iframes?

2022-07-28 08:05 UTC, remusao commented on packages/adblocker-webextension/adblocker.ts
> +    const codeRunningInPage = `(function(){
We might want to use this function as well to wrap the script? https://github.com/ghostery/adblocker/blob/b11cb64f59153becab6f37f2cca4cf1228f11a06/packages/adblocker-content/adblocker.ts#L236

And maybe mimic this for the logic below: https://github.com/ghostery/adblocker/blob/b11cb64f59153becab6f37f2cca4cf1228f11a06/packages/adblocker-content/adblocker.ts#L255

2022-08-12 14:57 UTC, philipp-classen commented
I'm closing this one (the follow-up PR is https://github.com/ghostery/adblocker/pull/2750)

2022-08-12 14:57 UTC, closed without merging