chore: fix linter exceptions
ghostery/adblocker pull request #4487
Opened 2024-12-03 04:08 UTC by seia-soto

This tries to fix exceptions by:
- replacing `do...while` to infinite `for(;;)` loop.
- dropping `any`.

2024-12-03 09:15 UTC, remusao commented on packages/adblocker-playwright/src/index.ts
This honestly looks more confusing than the do/while(true). Why not disable the lint if it does not bring value for theses cases instead?

2024-12-03 11:47 UTC, chrmod requested changes

2024-12-03 11:47 UTC, chrmod commented on packages/adblocker-playwright/src/index.ts
same here, would prefer to use do/while

2024-12-05 10:33 UTC, seia-soto commented on packages/adblocker-playwright/src/index.ts
Updated!

2024-12-09 08:40 UTC, chrmod approved these changes

2024-12-09 11:23 UTC, merged