feat: `$removeparam`
ghostery/adblocker pull request #4528
Opened 2024-12-13 07:11 UTC by seia-soto

This adds experimental `$removeparam` support for adblocker.

`$removeparam` is slightly different from the redirect filters we've seen because multiple filters could interact with single request. We need to clarify the way of providing filters applied.

- We don't need to run both resource redirect filters and `removeparam` filters.
- If we see `removeparam` filter, we need to prioritize this as it changes the request not the response. Resource redirects can be applied after the request redirect.

2024-12-23 08:29 UTC, chrmod reviewed
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/URLTransform

2024-12-23 09:08 UTC, seia-soto commented
Note: we're going to apply filters one by one

2024-12-25 10:29 UTC, seia-soto commented
Leaving a note: regexp wrapping: `[\\?&](${value!.slice(1, flagSeparatorIndex)}[^=]*)`

2025-01-04 07:28 UTC, remusao commented on packages/adblocker/src/filters/network.ts
> +            if (negation || value.startsWith('/')) {
Should we also check that value is not an empty string here?

2025-01-04 07:28 UTC, remusao commented on packages/adblocker/src/filters/network.ts
> +    return this.optionValue || '';
We should probably never return an empty string here.

2025-01-04 07:28 UTC, remusao commented on packages/adblocker/src/filters/network.ts
> +        options.push('removeparam');
Is this used for exceptions?

2025-01-04 07:28 UTC, remusao commented on packages/adblocker/test/parsing.test.ts
> +      it('parses removeparam without a value', () => {
Does this mean to remove all query parameters?

2025-01-04 07:28 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +          const searchParamsSeparatorAt = request.url.indexOf('?');
It might be best to use a real URL parser (`new URL(request.url)`) to avoid some quirks and simplify the implementation.

2025-01-06 05:45 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +            if (negation || value.startsWith('/')) {
Empty string means to remove all params from url. We should accept it here.

2025-01-06 05:45 UTC, seia-soto commented on packages/adblocker/test/parsing.test.ts
> +      it('parses removeparam without a value', () => {
Exactly

2025-01-06 05:58 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +          const searchParamsSeparatorAt = request.url.indexOf('?');
Fixed in 9c1e12b1dc1b60bc68d026427823166eff73d0a2

2025-01-06 05:58 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +        options.push('removeparam');
It's being used to remove all params.

2025-01-06 06:02 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +    return this.optionValue || '';
Correct, I checked that there's no chance of `optionValue` to be undefined.

2025-01-08 14:56 UTC, chrmod reviewed
Does this support exceptions like `$removeparam=igshid,domain=instagram.com|threads.net`?

2025-01-08 14:56 UTC, chrmod commented on packages/adblocker/src/filters/network.ts
> +      if (this.removeparam!.length > 0) {
wont this throw if `this.removeparam === undefined` ?

2025-01-10 13:58 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +      if (this.removeparam!.length > 0) {
`removeparam` is always `string` here. I'll add some comments or improve the type clarity.

2025-01-13 08:42 UTC, chrmod commented on packages/adblocker/src/filters/network.ts
> +      if (this.removeparam!.length > 0) {
shouldn't this type change then?
```
public get removeparam(): string | undefined {
```
https://github.com/ghostery/adblocker/pull/4528/files#diff-f45592ce8a6bd8a6e8e39391572f4a38406614b3649a6628891ca6fc38a516a9R1279

2025-01-13 09:10 UTC, chrmod commented on packages/adblocker/src/engine/engine.ts
> +                redirectUrl = request.url.slice(0, request.url.indexOf('?'));
This will also remove the anchors `#` at the end of the URL

2025-01-14 10:12 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +                redirectUrl = request.url.slice(0, request.url.indexOf('?'));
The part after `#` (hashtag fragment) is not sent to the server at all and shouldn't be included there.

2025-01-14 10:30 UTC, seia-soto commented on packages/adblocker/test/engine/engine.test.ts
> +        const engine = createEngine('||foo.com$removeparam');
fixed in 533110ecee31387ea0d6c3881886b35f6d30cd9b

2025-01-14 10:31 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +      if (this.removeparam!.length > 0) {
- Other methods like `get csp()` has a same shape.
- We use an empty value for the full removal of parameters.

2025-01-27 04:48 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +    mask >>>= 0;
Problematic part: https://github.com/ghostery/adblocker/pull/4528/files#diff-f45592ce8a6bd8a6e8e39391572f4a38406614b3649a6628891ca6fc38a516a9R981-R987

2025-01-30 10:16 UTC, chrmod requested changes
Lets move out the bit operations safety out of this PR. Besides, it looks good imo.

2025-01-31 10:24 UTC, seia-soto commented
Waiting for #4634

2025-02-06 16:50 UTC, chrmod commented on packages/adblocker/src/filters/network.ts
> +    mask >>>= 0;
@seia-soto can this be removed now?

2025-02-08 20:47 UTC, remusao requested changes
The AdGuard documentation mentions:

> Please note that such rules are only applied to GET, HEAD, OPTIONS, and sometimes POST requests.

Where do we intend to perform those checks?

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +            redirects.push(filter);
Why do we store removeparam as redirect rules? Aren't they of different nature?

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +              removeparamExceptionFilters.set(filter.removeparam!, filter);
I think it might be possible to inform the type checker from `isRemoveParam` that `filter.removeparam` is not undefined/null.

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +              removeparamFilters.set(filter.removeparam!, filter);
Is it safe to use `removeparam` as a key in a Set? What about other possible constraints like 1p/3p, or request type such as script/xhr/etc.

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +        if (result.filter === undefined && redirectFilters.length !== 0) {
What is the rational behind giving priority to removeparam over redirects? Wouldn't it make sense to do it the other way around? A redirect rule is a block rule + a redirect rule (as per uBO semantics). Hence if a request is blocked it should have priority over keeping the request and remove some of the parameters.

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/src/filters/network.ts
> +            // TODO: Support regex
How about `~` negation supported by AdGuard? I see it might be handled below but maybe worth documenting the limitation (and having a unit test for each)

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/src/filters/network.ts
> +    mask >>>= 0;
Is this still required after the other PR to generalize the use of setBit has been merged?

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/test/parsing.test.ts
> +        network('||fo.com$~removeparam', null);
How about `removeparam=~param` which seems to be supported by AdGuard (and referenced from uBO; unclear if uBO supports that). Let's make sure we reject these filters if we don't support them.

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/src/filters/network.ts
> +        options.push(`removeparam=${this.optionValue}`);
Nit. Maybe we don't need to mix the use of three different methods/getters.
```suggestion
    const removeparam = this.removeparam;
    if (removeparam !== undefined) {
      if (removeparam.length > 0) {
        options.push(`removeparam=${removeparam}`);
```

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/src/filters/network.ts
> +          case 'removeparam':
Nit. Since it would be invalid to have filters with a combination of `removeparam` and another `optionValue`, can we add a check to reject filters that try to combine at least two of these options?

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +                result.filter = filter;
That seems invalid in case there is more than one `removeparam` filter applying to the URL. I also think that in terms of semantics, the `result.filter` means a blocking filter, but removeparam filters aren't blocking requests. Maybe would it make more sense to add an additional key on `result` with a list of removeparams (or if we want to generalize, a list of URL/request modifiers)

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/test/engine/engine.test.ts
> +        }
It is surprising to me that we need to call the `.match(...)` multiple times to remove all params. Shouldn't a single call to `.match(...)` remove all matching params in a single pass?

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +            };
It seems a bit counter-intuitive to me to reuse the dataUrl in order to express the removeparam result. Why not return a list of URL modifiers to be interpreted by the client code and adapted based on available capability of the platform? (iOS, Manifest v2, Manifest v3, might not have the best way to modify request parameters) Ideally the adblocker library should not need to think about these considerations and return a more "abstract" kind of response.

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/test/engine/engine.test.ts
Can we add more tests for corner cases? For example: if we have a global `$removeparam` and also `@@||example.org$removeparam=utm`, do we remove all parameters or skip `utm`?

2025-02-08 20:47 UTC, remusao commented on packages/adblocker/test/parsing.test.ts
Let's add a test case to cover the regexp removeparam case (as being unsupported for now)

2025-02-08 21:00 UTC, seia-soto commented on packages/adblocker/test/engine/engine.test.ts
> +        }
We didn't know how to return the filters matched since the return type allows only one filter to be returned. That means not the all of filters matched will be sent to the return value of `match` unless we change the shape.

2025-02-10 02:28 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +            redirects.push(filter);
They're different but removeparam is implemented using redirection.

2025-02-10 02:31 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +    mask >>>= 0;
Nope, this now should be removed.

2025-02-10 07:00 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +    mask >>>= 0;
Fixed by https://github.com/ghostery/adblocker/pull/4528/commits/09ea7e724836c7e8683a05ef95556da7b97f7e20

2025-02-10 07:00 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +    mask >>>= 0;
fixed by https://github.com/ghostery/adblocker/pull/4528/commits/09ea7e724836c7e8683a05ef95556da7b97f7e20

2025-02-10 07:01 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +              removeparamExceptionFilters.set(filter.removeparam!, filter);
I think it's happening because I defined it as `getter`.

2025-02-10 07:02 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +              removeparamFilters.set(filter.removeparam!, filter);
those conditions (1p, 3p, and request types) should be handled in the network filter matching process.

2025-02-10 07:04 UTC, seia-soto commented on packages/adblocker/test/parsing.test.ts
> +        network('||fo.com$~removeparam', null);
Those tests are responsible for that. uBo marks `~removeparam` as an invalid option.

2025-02-10 07:04 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +          case 'removeparam':
That's good idea, I think we can do it in a separate PR instead. `removeparam` is not only the filter option involving `optionValue`.

2025-02-10 07:08 UTC, seia-soto commented on packages/adblocker/test/engine/engine.test.ts
I included the priority before by testing one by one. It's defined in `engine.test.ts`.

```
// 1st priority: @@||<entity>$removeparam
// 2nd priority: ||<entity>$removeparam
// 3rd priority: @@||<entity>$removeparam=x
// 4th priority: ||<entity>$removeparam=x
```

```ts
      describe('exceptions', () => {
        let request: Request;
        before(() => {
          request = urlToDocumentRequest('https://foo.com/?x=y');
        });

        it('respects exception', () => {
          const engine = createEngine(`||foo.com$removeparam=x
@@||foo.com$removeparam=x`);
          expect(engine.match(request).match).to.be.false;
        });
        it('respects option value with exception', () => {
          const engine = createEngine(`||foo.com$removeparam=x
@@||foo.com$removeparam=y`);
          expect(engine.match(request).match).to.be.true;
        });

        it('priorities global removeparam over singular exception', () => {
          const engine = createEngine(`@@||foo.com$removeparam=x
||foo.com$removeparam`);
          expect(engine.match(request).match).to.be.true;
        });
        it('priorities global exception over global removeparam', () => {
          const engine = createEngine(`||foo.com$removeparam
@@||foo.com$removeparam`);
          expect(engine.match(request).match).to.be.false;
        });
      });
```

2025-03-03 13:17 UTC, seia-soto commented on packages/adblocker/test/parsing.test.ts
fixed by 166eecddc6fa6c8d4aa539302a9a28c565ba4c01

2025-03-03 13:21 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +            };
Fixed by 76e6a5128c1bcb61bced742e2a2868f38bc19c9d

2025-03-03 13:23 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +        if (result.filter === undefined && redirectFilters.length !== 0) {
Fixed by 76e6a5128c1bcb61bced742e2a2868f38bc19c9d

2025-03-03 13:31 UTC, seia-soto commented on packages/adblocker/test/parsing.test.ts
> +        network('||fo.com$~removeparam', null);
Continuing in https://github.com/ghostery/adblocker/pull/4528#discussion_r1947942150

2025-03-03 13:35 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +            redirects.push(filter);
Outdated.

2025-03-03 13:43 UTC, seia-soto commented on packages/adblocker/test/engine/engine.test.ts
> +        }
Outdated.

2025-03-03 13:44 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +                result.filter = filter;
Outdated. Shape changed.

2025-03-20 04:27 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +            // TODO: Support regex
Leaving a note: from their documentation (Inversion section under `$removeparam` modifier; https://adguard.com/kb/general/ad-filtering/create-own-filters/#removeparam-modifier), it's a different one.

2025-03-20 04:53 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +            // TODO: Support regex
It's now supported [`200515e` (#4528)](https://github.com/ghostery/adblocker/pull/4528/commits/200515e7d126b0f258eab13d47a445a86ff0323a)

2025-03-21 20:10 UTC, remusao commented on packages/adblocker/src/codebooks/network-substitude.ts
Is the data really big enough to justify compressing it? What is the accumulated size of all remove param strings? And how much is it when compressed with Smaz?

2025-03-21 20:10 UTC, remusao commented on packages/adblocker/src/codebooks/network-substitude.ts
Is the data really big enough to justify compressing it? What is the accumulated size of all remove param strings? And how much is it when compressed with Smaz?

2025-03-21 20:14 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +          if (this.config.enableHtmlFiltering) {
How are `enableHtmlFiltering` and `removeparam` related?

2025-03-23 09:31 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +          if (this.config.enableHtmlFiltering) {
`removeparam` requires html filtering capability even if they don't pass the html filtering code flow. Alternatively, I believe html filtering isn't the one I'd like to express but it's the closest existing in the library.

2025-03-24 11:19 UTC, seia-soto commented on packages/adblocker/src/codebooks/network-substitude.ts
From the current branch of adblocker assets, it shows:

`compressed=3506B plain=5057B (ratio: 0.6932964208028476)`

I believe that having a compression codebook for `removeparam` is really nice because many of tracking parameters are shared across multiple websites. `utm` is a great example of this.

2025-03-24 11:42 UTC, remusao commented on packages/adblocker/src/codebooks/network-substitude.ts
So we're saving 3KB? If so I don't think it's worth the trouble.

2025-03-24 11:47 UTC, seia-soto commented on packages/adblocker/src/codebooks/network-substitude.ts
I can skip creating a codebook for that but still keeping a new filter bucket looks worth it to simplify the matching codeflow: `substitudes`. What do you think?

2025-03-24 16:01 UTC, remusao commented on packages/adblocker/src/filters/network.ts
> +          case 'removeparam':
Sounds good, let's please open an issue to not forget about it.

2025-03-24 16:27 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +  substitude:
? Nit. I'm also not sure how to understand the name `substitute`. Can we make it more specific? Maybe `mutatedUrl` or `modifiedUrl` or `rewrittenUrl`?
```suggestion
  substitute:
```

2025-03-24 16:27 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +        filters: Map<NetworkFilter, NetworkFilter | undefined>;
Why return a `Map` here?

2025-03-24 16:27 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +    this.substitudes = new NetworkFilterBucket({ config: this.config });
If the bucket is specifically about removeparam, why give it another name?
```suggestion
    // $removeparam
    this.removeparams = new NetworkFilterBucket({ config: this.config });
```

2025-03-24 16:27 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +      // 2. redirection ($removeparam and $redirect=resource)
Is this comment up-to-date?

2025-03-24 16:27 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> -          .sort((a, b) => b.getRedirectPriority() - a.getRedirectPriority());
Nit. That seems like an unnecessary change.

2025-03-24 16:27 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +          const url = new URL(request.url);
Nit. Let's only parse the URL if we have a match since we won't have any for the vast majority of calls.

2025-03-24 16:27 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +          result.substitude = {
In case there was a redirect + exception before, should we do something about `result.filter` and `result.exception`?

2025-03-25 08:47 UTC, seia-soto commented on packages/adblocker/src/codebooks/network-substitude.ts
Oh, it's already removed in 6b1a6e6758a8e864ab989d63ceb088ebda897c9d , sorry for not mentioning this.

2025-03-25 09:42 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +  substitude:
After thinking a bit, I feel having a term of "action" as a top level property name looks promising. Therefore, I took `urlRewrite` or maybe `urlMutation` for a top level property name.

```
export interface BlockingResponse {
  match: boolean;
  redirect:
    | undefined
    | {
        body: string;
        contentType: string;
        dataUrl: string;
      };
  urlRewrite:
    | undefined
    | {
        rewrittenUrl: string;
        filters: NetworkFilter[];
      };
```

Do you think this structure is clear?

2025-03-25 09:43 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +        filters: Map<NetworkFilter, NetworkFilter | undefined>;
It implies exceptions. I should have more verbosity in the code here.

2025-03-25 11:57 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> -          .sort((a, b) => b.getRedirectPriority() - a.getRedirectPriority());
Fixed in 22cd3d71075ce5279916e6b88f56fbbde657beee

2025-03-25 13:21 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +          result.substitude = {
Updated in 22cd3d71075ce5279916e6b88f56fbbde657beee but not sure if it matches your thought. Please, check the following section: [`22cd3d7` (#4528)](https://github.com/ghostery/adblocker/pull/4528/commits/22cd3d71075ce5279916e6b88f56fbbde657beee#diff-0a5765da7fa865c0ab71fc7b0187e3c6663bcc602558022d04dd7da3c0ab410aR1540-R1549)

2025-03-25 13:21 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +          const url = new URL(request.url);
Updated in 22cd3d71075ce5279916e6b88f56fbbde657beee but not sure if it matches your thought. Please, check the following section: [`22cd3d7` (#4528)](https://github.com/ghostery/adblocker/pull/4528/commits/22cd3d71075ce5279916e6b88f56fbbde657beee#diff-0a5765da7fa865c0ab71fc7b0187e3c6663bcc602558022d04dd7da3c0ab410aR1540-R1549)

2025-03-25 13:22 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +      // 2. redirection ($removeparam and $redirect=resource)
Fixed in 22cd3d71075ce5279916e6b88f56fbbde657beee

2025-03-25 13:22 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +  substitude:
This was updated in 22cd3d71075ce5279916e6b88f56fbbde657beee, please check.

2025-03-25 13:23 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +          if (this.config.enableHtmlFiltering) {
I removed the flag requirement in 22cd3d71075ce5279916e6b88f56fbbde657beee but keeping in mind about having more variable.

2025-03-25 13:32 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +          result.substitude = {
It'll directly impact to `result.matched`, so I feel it's reasonable to set values again once the lib finds a match in `removeparam`. However, the question is what to put in `result.filter` which only accepts one filter object.

2025-03-25 15:34 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +          case 'removeparam':
Opened here https://github.com/ghostery/adblocker/issues/4763

2025-03-26 08:51 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +              removeparamFilters.set(filter.removeparam!, filter);
I don't see a problem in that situation. At least, it doesn't seem to create a problem or breakage. The only difference I can see is that we will be able to make them reported to user by keeping them all.

2025-05-21 14:59 UTC, chrmod requested changes

2025-05-30 07:39 UTC, seia-soto commented
Bringing dependency up to date to avoid conflict.

2025-05-30 07:50 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +                  searchParams = new URLSearchParams(request.url.slice(searchParamSeparatorIndex));
fixed by e878d4c1a05c8af0acb624878c7439bd84978da8

2025-05-30 07:58 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +            const getSearchParams = (() => {
fixed in fdf15e182ccb2e02a2aa8fe9cb676cd05755fb2d

2025-05-30 07:59 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +            result.urlRewrite = {
`rewrittenUrl` is optional string. `undefined` here means there's no `urlRewrite` but there are exception filters.

2025-05-30 08:21 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +            result.urlRewrite = {
fixed in ffdf78980659dbae7ac63fc8985886c346d60958

2025-05-30 08:24 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +        this.emit(
fixed in e6f5f786f26d257242526c0e496d62372749c2b0

2025-05-30 08:35 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +        if (result.filter === undefined || result.exception !== undefined) {
fixed in c3292fe0684b8cb68bf378cda926f2e4fc1f8e3f

2025-06-02 08:59 UTC, chrmod commented on packages/adblocker/src/engine/engine.ts
> +    if (withMetadata === true && this.metadata) {
lets revert it for now - I don't think `removeparam` filters will be very useful to name trackers.

2025-06-02 09:11 UTC, chrmod commented on packages/adblocker/src/engine/engine.ts
> +  urlRewrite:
I struggle with this interface. On one hand, `removeparam` is just a redirect, but the `redirect` type here is very much coupled with `Resources` and extending it would be a breaking change. 

Additionally, I'm not sure if we need to list `removeparam` filters with exceptions - we don't do it for redirects. Event emitter can provide information about matched filters.

2025-06-02 09:18 UTC, chrmod commented on packages/adblocker/src/engine/engine.ts
> +  urlRewrite:
lets call it `rewrite`

2025-06-02 09:18 UTC, chrmod commented on packages/adblocker/src/engine/engine.ts
> +        rewrittenUrl: undefined | string;
lets call it `url`

2025-06-02 09:19 UTC, chrmod commented on packages/adblocker/src/engine/engine.ts
> +        filters: Map<NetworkFilter, NetworkFilter | undefined>;
maybe we can drop it in the first iteration ?

2025-06-04 07:20 UTC, chrmod commented on packages/adblocker/src/engine/engine.ts
> +        if (result.filter === undefined) {
Would it be possible to split `match` in this way?
```suggestion
        if (result.filter === undefined) {
          result.rewrite = this.matchRemoveParam(request);
        }
```

2025-06-04 09:16 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +import { URLSearchParams } from '@ghostery/url-parser';
Why not use the native implementation? As far as I know it's available in all environments including Node.js.

2025-06-04 10:28 UTC, chrmod commented on packages/adblocker/src/engine/engine.ts
> +import { URLSearchParams } from '@ghostery/url-parser';
That's a good question. I've took assumption that as adblocker does not rely on standard `URL` API, it should also avoid `URLSearchParams`. That should make it more portable.

On the other hand, if someone with esoteric use case (like we had at Cliqz) can always polify that API. 

@seia-soto sorry for the unnecessary work. If Remi is fine to use the standard API than I think we can drop `@ghostery/url-parser`

2025-06-04 11:42 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +import { URLSearchParams } from '@ghostery/url-parser';
I think so far we didn't use `URL` because there was no need. We only needed domain parsing, for which we used `tldts`. I'm not necessarily against using the `@ghostery/url-parser`, just curious why that was. Also, how much does it add to the minified bundle?

2025-06-06 07:15 UTC, chrmod commented on packages/adblocker/src/engine/engine.ts
> +import { URLSearchParams } from '@ghostery/url-parser';
With `url-parser` the minified bundle is `120.6 KiB` and `118.8 KiB` without.

2025-06-06 07:18 UTC, chrmod approved these changes

2025-06-06 07:54 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +import { URLSearchParams } from '@ghostery/url-parser';
Sounds reasonable

2025-06-06 07:56 UTC, remusao approved these changes

2025-06-06 07:56 UTC, remusao commented on packages/adblocker/src/filters/network.ts
> +  isRemoveParam = 1 << 31,
To confirm, we're fine with negative numbers as mask?

2025-06-07 07:11 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +            searchParamSeparatorIndex !== request.url.length - 1
Should this be (otherwise I think it's always evaluated to `true`):
```suggestion
            searchParamSeparatorIndex !== -1 &&
            searchParamSeparatorIndex !== request.url.length - 1
```

If that change is correct, let's add a unit test to cover that.

2025-06-07 07:11 UTC, remusao commented on packages/adblocker/src/engine/engine.ts
> +            result.rewrite = {
Should we set this only when `modified` above is `true`?

2025-06-07 07:11 UTC, remusao commented on packages/adblocker/test/engine/engine.test.ts
> +            expect(rewrite?.url ?? request.url).not.to.include('utm=');
Where is `request` defined?

2025-06-09 04:17 UTC, seia-soto commented on packages/adblocker/test/engine/engine.test.ts
> +            expect(rewrite?.url ?? request.url).not.to.include('utm=');
`request` is defined at the top of redirect description section.

2025-06-09 04:18 UTC, seia-soto commented on packages/adblocker/src/filters/network.ts
> +  isRemoveParam = 1 << 31,
Yes, it is addressed by #4634 and integrity tests.

2025-06-09 04:18 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +            result.rewrite = {
fixed in 8f87db81a3564ae1c59c4ea934a99c3e25cbec0a

2025-06-09 04:19 UTC, seia-soto commented on packages/adblocker/src/engine/engine.ts
> +            searchParamSeparatorIndex !== request.url.length - 1
fixed in 8f87db81a3564ae1c59c4ea934a99c3e25cbec0a

2025-06-09 07:09 UTC, merged